alias workspace="cd ${GITPOD_REPO_ROOT}"
alias webui="gp preview $(gp url 8080)"
alias temporal="/home/gitpod/.temporalio/bin/temporal"
alias tctl="/home/gitpod/.temporalio/bin/tctl"
echo "Your workspace is located at: ${GITPOD_REPO_ROOT}"
echo "Type the command     workspace      to return to the workspace directory at any time."
